name: angular_transformers
version: 0.0.1
description: Pub build transformers for Angular
homepage: https://github.com/angular/angular_transformers.dart
environment:
  sdk: '>=1.0.0'
dependencies:
  args: ">=0.9.0 <0.10.0"
  analyzer: ">=0.11.0 <0.12.0"
  angular:
    path: ../angular.dart
  barback: ">=0.9.0 <0.12.0"
  collection: '>=0.9.1 <1.0.0'
  di:
    path: ../di.dart
  html5lib: '>=0.8.7 <0.10.0'
  inject: '<0.1.0'
  unittest: '>=0.8.7 <0.10.0'
  yaml: ">=0.9.0 <0.10.0"
dev_dependencies:
  browser: '>=0.8.7 <0.10.0'
