name: di_test
version: 0.0.32
description: Test for generating files for DI
dependencies:
  angular_transformers:
    path: ../..
  di:
    path: ../../../di.dart
dev_dependencies:
  benchmark_harness: any
  unittest: any
  browser: any
